import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Center,
  Flex,
  Spacer,
  Text,
  Box,
  Grid,
  Image,
  SimpleGrid,
  Button,
  Link,
  GridItem,
  Stack,
} from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Y書店</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Box bg="#0e1131" w="100%" h="10vh" color="white">
          <Box>
            <Flex>
              <Link href="./" style={{ textDecoration: "none" }}>
                <Text fontSize="6xl" ml="20px">
                  Y書店
                </Text>
              </Link>

              <Spacer />

              <Grid templateColumns="repeat(5, 1fr)" gap={6} mt="20px">
                <Text>今月のおすすめ</Text>
                <Text>イベント</Text>
                <Text>店舗一覧</Text>
                <Text>よくある質問</Text>
                <Text>企業理念</Text>
              </Grid>
              {/* <Stack direction={["column", "row"]} spacing="24px">
                <Text>今月のおすすめ</Text>
                <Text>イベント</Text>
                <Text>店舗一覧</Text>
                <Text>よくある質問</Text>
                <Text>企業理念</Text>
              </Stack> */}
            </Flex>
          </Box>
          <Box>
            <Link href="/logIn">
              <Button bg="#d7bc61">ログイン</Button>
            </Link>
          </Box>
        </Box>
      </header>

      <highlight>
        <Center>
          <Box boxSize="80%">
            <Image src="/books.jpg" alt="Dan Abramov" />
          </Box>
        </Center>
      </highlight>

      <news>
        <Center>
          <Text fontSize="6xl">NEWS</Text>
        </Center>
      </news>

      <footer>
        <Box bg="#0e1131" w="100%" h="5vh" color="white">
          <Text></Text>
        </Box>
      </footer>
    </div>
  );
}
