import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Center,
  Flex,
  Spacer,
  Text,
  Box,
  Grid,
  Stack,
  FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Input,
  Link,
  Button,
} from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Y書店</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Box bg="#0e1131" w="100%" h="10vh" color="white">
          <Flex>
            <Link href="../" style={{ textDecoration: "none" }}>
              <Text fontSize="6xl" ml="20px">
                Y書店
              </Text>
            </Link>

            <Spacer />
            <Grid templateColumns="repeat(5, 1fr)" gap={6} mt="20px">
              <Text>今月のおすすめ</Text>
              <Text>イベント</Text>
              <Text>店舗一覧</Text>
              <Text>よくある質問</Text>
              <Text>企業理念</Text>
            </Grid>
          </Flex>
        </Box>
      </header>
      <Box p="40px">
        <Box borderWidth="2px" p="20px">
          <Center>
            <Text fontSize="5xl">ログイン</Text>
          </Center>

          <FormControl>
            <FormLabel>メールアドレス</FormLabel>
            <Input type="email" />
            {/* <FormHelperText></FormHelperText> */}
          </FormControl>

          <FormControl mt="20px">
            <FormLabel>パスワード</FormLabel>
            <Input type="password" />
            {/* <FormHelperText></FormHelperText> */}
          </FormControl>
          <Stack mt="30px">
            <Link color="blue" href="/signIn">
              新規会員登録はこちら
            </Link>
            <Link color="blue">パスワードをお忘れの方</Link>
          </Stack>

          <Box>
            <Center>
              <Link href="/logIn">
                <Button bg="#d7bc61">ログイン</Button>
              </Link>
            </Center>
          </Box>
        </Box>
      </Box>

      <footer>
        <Box bg="#0e1131" w="100%" h="5vh" color="white">
          <Text></Text>
        </Box>
      </footer>
    </div>
  );
}
