import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Center,
  Flex,
  Spacer,
  Text,
  Box,
  Grid,
  Container,
  FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Input,
  Link,
  Button,
  HStack,
  RadioGroup,
  Radio,
  NumberInput,
  NumberInputField,
  NumberInputStepper,
  NumberIncrementStepper,
  NumberDecrementStepper,
  Stack,
} from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Y書店</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Box bg="#0e1131" w="100%" h="10vh" color="white">
          <Flex>
            <Link href="../" style={{ textDecoration: "none" }}>
              <Text fontSize="6xl" ml="20px">
                Y書店
              </Text>
            </Link>
            <Spacer />
            <Grid templateColumns="repeat(5, 1fr)" gap={6} mt="20px">
              <Text>今月のおすすめ</Text>
              <Text>イベント</Text>
              <Text>店舗一覧</Text>
              <Text>よくある質問</Text>
              <Text>企業理念</Text>
            </Grid>
          </Flex>
        </Box>
      </header>
      <Box p="40px">
        <Box borderWidth="2px" p="20px">
          <Stack spacing="20px">
            <Center>
              <Text fontSize="5xl">新規会員登録</Text>
            </Center>
            <FormControl isRequired>
              <FormLabel>メールアドレス</FormLabel>
              <Input type="email" />
              {/* <FormHelperText></FormHelperText> */}
            </FormControl>
            <FormControl isRequired>
              <FormLabel>パスワード</FormLabel>
              <Input type="password" />
              {/* <FormHelperText></FormHelperText> */}
            </FormControl>

            <FormControl isRequired>
              <FormLabel>お名前</FormLabel>
              <Input placeholder="name" />
            </FormControl>
            <FormLabel>生年月日</FormLabel>
            <HStack>
              <FormControl>
                <NumberInput max={2022} min={1900} defaultValue={2000}>
                  <NumberInputField />
                  <NumberInputStepper>
                    <NumberIncrementStepper />
                    <NumberDecrementStepper />
                  </NumberInputStepper>
                </NumberInput>
              </FormControl>
              <FormLabel>年</FormLabel>
              <FormControl>
                <NumberInput max={12} min={1} defaultValue={1}>
                  <NumberInputField />
                  <NumberInputStepper>
                    <NumberIncrementStepper />
                    <NumberDecrementStepper />
                  </NumberInputStepper>
                </NumberInput>
              </FormControl>
              <FormLabel>月</FormLabel>
              <FormControl>
                <NumberInput max={1} min={31} defaultValue={1}>
                  <NumberInputField />
                  <NumberInputStepper>
                    <NumberIncrementStepper />
                    <NumberDecrementStepper />
                  </NumberInputStepper>
                </NumberInput>
              </FormControl>
              <FormLabel>日</FormLabel>
            </HStack>
            <FormControl as="fieldset" isRequired>
              <FormLabel as="sex">性別</FormLabel>
              <RadioGroup defaultValue="その他">
                <HStack spacing="24px">
                  <Radio value="男性">男性</Radio>
                  <Radio value="女性">女性</Radio>
                  <Radio value="その他">その他</Radio>
                </HStack>
              </RadioGroup>
            </FormControl>
            <Link color="blue">ログイン</Link>

            <Link color="blue">パスワードをお忘れの方</Link>
            <Box>
              <Center>
                <Link href="/login">
                  <Button bg="#d7bc61">新規会員登録する</Button>
                </Link>
              </Center>
            </Box>
          </Stack>
        </Box>
      </Box>

      <footer>
        <Box bg="#0e1131" w="100%" h="5vh" color="white">
          <Text></Text>
        </Box>
      </footer>
    </div>
  );
}
